/* ************************************
AG_FINEGRAINEDAUDITING
AG_MANHL
AG_MANHL_BND
AG_MANHL_WALL
AG_META_UPDLOG
G3E_DUCTIFACE
G3E_DUCTFORMATION
************************************* */




DROP PUBLIC SYNONYM AG_FINEGRAINEDAUDITING;
CREATE OR REPLACE PUBLIC SYNONYM AG_FINEGRAINEDAUDITING FOR NEPS.AG_FINEGRAINEDAUDITING;
GRANT DELETE, INSERT, UPDATE ON AG_FINEGRAINEDAUDITING TO ADMINISTRATOR;
GRANT SELECT ON AG_FINEGRAINEDAUDITING TO DESIGNER;
GRANT SELECT ON AG_FINEGRAINEDAUDITING TO FINANCE;
GRANT SELECT ON AG_FINEGRAINEDAUDITING TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON AG_FINEGRAINEDAUDITING TO SUPERVISOR;

DROP PUBLIC SYNONYM AG_MANHL;
CREATE OR REPLACE PUBLIC SYNONYM AG_MANHL FOR NEPS.AG_MANHL;
GRANT DELETE, INSERT, UPDATE ON AG_MANHL TO ADMINISTRATOR;
GRANT SELECT ON AG_MANHL TO DESIGNER;
GRANT SELECT ON AG_MANHL TO FINANCE;
GRANT SELECT ON AG_MANHL TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON AG_MANHL TO SUPERVISOR;

DROP PUBLIC SYNONYM AG_MANHL_BND;
CREATE OR REPLACE PUBLIC SYNONYM AG_MANHL_BND FOR NEPS.AG_MANHL_BND;
GRANT DELETE, INSERT, UPDATE ON AG_MANHL_BND TO ADMINISTRATOR;
GRANT SELECT ON AG_MANHL_BND TO DESIGNER;
GRANT SELECT ON AG_MANHL_BND TO FINANCE;
GRANT SELECT ON AG_MANHL_BND TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON AG_MANHL_BND TO SUPERVISOR;


DROP PUBLIC SYNONYM AG_MANHL_WALL;
CREATE OR REPLACE PUBLIC SYNONYM AG_MANHL_WALL FOR NEPS.AG_MANHL_WALL;
GRANT DELETE, INSERT, UPDATE ON AG_MANHL_WALL TO ADMINISTRATOR;
GRANT SELECT ON AG_MANHL_WALL TO DESIGNER;
GRANT SELECT ON AG_MANHL_WALL TO FINANCE;
GRANT SELECT ON AG_MANHL_WALL TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON AG_MANHL_WALL TO SUPERVISOR;

DROP PUBLIC SYNONYM AG_META_UPDLOG;
CREATE OR REPLACE PUBLIC SYNONYM AG_META_UPDLOG FOR NEPS.AG_META_UPDLOG;
GRANT DELETE, INSERT, UPDATE ON AG_META_UPDLOG TO ADMINISTRATOR;
GRANT SELECT ON AG_META_UPDLOG TO DESIGNER;
GRANT SELECT ON AG_META_UPDLOG TO FINANCE;
GRANT SELECT ON AG_META_UPDLOG TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON AG_META_UPDLOG TO SUPERVISOR;



DROP PUBLIC SYNONYM G3E_DUCTIFACE;
CREATE OR REPLACE PUBLIC SYNONYM G3E_DUCTIFACE FOR NEPS.G3E_DUCTIFACE;
GRANT DELETE, INSERT, UPDATE ON G3E_DUCTIFACE TO ADMINISTRATOR;
GRANT SELECT ON G3E_DUCTIFACE TO DESIGNER;
GRANT SELECT ON G3E_DUCTIFACE TO FINANCE;
GRANT SELECT ON G3E_DUCTIFACE TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON G3E_DUCTIFACE TO SUPERVISOR;


DROP PUBLIC SYNONYM G3E_DUCTFORMATION;
CREATE OR REPLACE PUBLIC SYNONYM G3E_DUCTFORMATION FOR NEPS.G3E_DUCTFORMATION;
GRANT DELETE, INSERT, UPDATE ON G3E_DUCTFORMATION TO ADMINISTRATOR;
GRANT SELECT ON G3E_DUCTFORMATION TO DESIGNER;
GRANT SELECT ON G3E_DUCTFORMATION TO FINANCE;
GRANT SELECT ON G3E_DUCTFORMATION TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON G3E_DUCTFORMATION TO SUPERVISOR;

DROP PUBLIC SYNONYM GC_CONTAIN;
CREATE OR REPLACE PUBLIC SYNONYM GC_CONTAIN FOR NEPS.GC_CONTAIN;
GRANT DELETE, INSERT, UPDATE ON GC_CONTAIN TO ADMINISTRATOR;
GRANT SELECT ON GC_CONTAIN TO DESIGNER;
GRANT SELECT ON GC_CONTAIN TO FINANCE;
GRANT SELECT ON GC_CONTAIN TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON GC_CONTAIN TO SUPERVISOR;

DROP PUBLIC SYNONYM GC_COND;
CREATE OR REPLACE PUBLIC SYNONYM GC_COND FOR NEPS.GC_COND;
GRANT DELETE, INSERT, UPDATE ON GC_COND TO ADMINISTRATOR;
GRANT SELECT ON GC_COND TO DESIGNER;
GRANT SELECT ON GC_COND TO FINANCE;
GRANT SELECT ON GC_COND TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON GC_COND TO SUPERVISOR;

DROP PUBLIC SYNONYM g3e_component;
CREATE OR REPLACE PUBLIC SYNONYM g3e_component FOR NEPS.g3e_component;
GRANT DELETE, INSERT, UPDATE ON g3e_component TO ADMINISTRATOR;
GRANT SELECT ON g3e_component TO DESIGNER;
GRANT SELECT ON g3e_component TO FINANCE;
GRANT SELECT ON g3e_component TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON g3e_component TO SUPERVISOR;

DROP PUBLIC SYNONYM g3e_featurecomponent;
CREATE OR REPLACE PUBLIC SYNONYM g3e_featurecomponent FOR NEPS.g3e_featurecomponent;
GRANT DELETE, INSERT, UPDATE ON g3e_featurecomponent TO ADMINISTRATOR;
GRANT SELECT ON g3e_featurecomponent TO DESIGNER;
GRANT SELECT ON g3e_featurecomponent TO FINANCE;
GRANT SELECT ON g3e_featurecomponent TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON g3e_featurecomponent TO SUPERVISOR;


DROP PUBLIC SYNONYM ref_civ_pole;
CREATE OR REPLACE PUBLIC SYNONYM ref_civ_pole FOR NEPS.ref_civ_pole;
GRANT DELETE, INSERT, UPDATE ON ref_civ_pole TO ADMINISTRATOR;
GRANT SELECT ON ref_civ_pole TO DESIGNER;
GRANT SELECT ON ref_civ_pole TO FINANCE;
GRANT SELECT ON ref_civ_pole TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON ref_civ_pole TO SUPERVISOR;

DROP PUBLIC SYNONYM ref_civ_riseratt;
CREATE OR REPLACE PUBLIC SYNONYM ref_civ_riseratt FOR NEPS.ref_civ_riseratt;
GRANT DELETE, INSERT, UPDATE ON ref_civ_riseratt TO ADMINISTRATOR;
GRANT SELECT ON ref_civ_riseratt TO DESIGNER;
GRANT SELECT ON ref_civ_riseratt TO FINANCE;
GRANT SELECT ON ref_civ_riseratt TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON ref_civ_riseratt TO SUPERVISOR;

DROP PUBLIC SYNONYM ref_civ_piercross;
CREATE OR REPLACE PUBLIC SYNONYM ref_civ_piercross FOR NEPS.ref_civ_piercross;
GRANT DELETE, INSERT, UPDATE ON ref_civ_piercross TO ADMINISTRATOR;
GRANT SELECT ON ref_civ_piercross TO DESIGNER;
GRANT SELECT ON ref_civ_piercross TO FINANCE;
GRANT SELECT ON ref_civ_piercross TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON ref_civ_piercross TO SUPERVISOR;

DROP PUBLIC SYNONYM ref_civ_subduct;
CREATE OR REPLACE PUBLIC SYNONYM ref_civ_subduct FOR NEPS.ref_civ_subduct;
GRANT DELETE, INSERT, UPDATE ON ref_civ_subduct TO ADMINISTRATOR;
GRANT SELECT ON ref_civ_subduct TO DESIGNER;
GRANT SELECT ON ref_civ_subduct TO FINANCE;
GRANT SELECT ON ref_civ_subduct TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON ref_civ_subduct TO SUPERVISOR;

DROP PUBLIC SYNONYM G3E_STYLERULE;
CREATE OR REPLACE PUBLIC SYNONYM G3E_STYLERULE FOR NEPS.G3E_STYLERULE;
GRANT DELETE, INSERT, UPDATE ON G3E_STYLERULE TO ADMINISTRATOR;
GRANT SELECT ON G3E_STYLERULE TO DESIGNER;
GRANT SELECT ON G3E_STYLERULE TO FINANCE;
GRANT SELECT ON G3E_STYLERULE TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON G3E_STYLERULE TO SUPERVISOR;

DROP PUBLIC SYNONYM ref_civ_ductpath;
CREATE OR REPLACE PUBLIC SYNONYM ref_civ_ductpath FOR NEPS.ref_civ_ductpath;
GRANT DELETE, INSERT, UPDATE ON ref_civ_ductpath TO ADMINISTRATOR;
GRANT SELECT ON ref_civ_ductpath TO DESIGNER;
GRANT SELECT ON ref_civ_ductpath TO FINANCE;
GRANT SELECT ON ref_civ_ductpath TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON ref_civ_ductpath TO SUPERVISOR;

