insert into G3E_CUSTOMCOMMAND (G3E_CCNO, G3E_USERNAME, G3E_AUTHOR, G3E_LARGEBITMAP, G3E_SMALLBITMAP, G3E_TOOLTIP, 
 G3E_COMMANDCLASS, G3E_ENABLINGMASK, G3E_MODALITY, G3E_SELECTSETENABLINGMASK, G3E_MENUORDINAL, G3E_INTERFACE)
 values (G3E_CUSTOMCOMMAND_SEQ.nextval, 'BulkMoveFeatures', 'Hazman', 0, 0, 'BulkMoveFeatures', 4, 8454160, 0, 0, 1, 
  'NEPS.BulkMoveFeatures:NEPS.GTechnology.BulkMoveFeatures.GTBulkMoveFeatures');
 
 insert into G3E_CUSTOMCOMMAND (G3E_CCNO, G3E_USERNAME, G3E_AUTHOR, G3E_LARGEBITMAP, G3E_SMALLBITMAP, G3E_TOOLTIP, 
 G3E_COMMANDCLASS, G3E_ENABLINGMASK, G3E_MODALITY, G3E_SELECTSETENABLINGMASK, G3E_MENUORDINAL, G3E_INTERFACE)
 values (G3E_CUSTOMCOMMAND_SEQ.nextval, 'MoveAndScale', 'Hazman', 0, 0, 'MoveAndScale', 4, 8454160, 0, 0, 1, 
  'NEPS.BulkMoveFeatures:NEPS.GTechnology.BulkMoveFeatures.GTMoveAndScale');
  
   
 insert into G3E_CUSTOMCOMMAND (G3E_CCNO, G3E_USERNAME, G3E_AUTHOR, G3E_LARGEBITMAP, G3E_SMALLBITMAP, G3E_TOOLTIP, 
 G3E_COMMANDCLASS, G3E_ENABLINGMASK, G3E_MODALITY, G3E_SELECTSETENABLINGMASK, G3E_MENUORDINAL, G3E_INTERFACE)
 values (G3E_CUSTOMCOMMAND_SEQ.nextval, 'MoveAssociatedFeatures', 'Hazman', 0, 0, 'MoveAssociatedFeatures', 4, 8454160, 0, 0, 1, 
  'NEPS.BulkMoveFeatures:NEPS.GTechnology.BulkMoveFeatures.GTMoveAssociatedFeatures');
   