
CREATE TABLE NEPS.REF_COPYSTREET
(
  FNO  VARCHAR2(40 BYTE)
);

CREATE OR REPLACE PUBLIC SYNONYM REF_COPYSTREET FOR NEPS.REF_COPYSTREET;
GRANT DELETE, INSERT, UPDATE ON NEPS.REF_COPYSTREET TO ADMINISTRATOR;
GRANT SELECT ON NEPS.REF_COPYSTREET TO DESIGNER;
GRANT SELECT ON NEPS.REF_COPYSTREET TO FINANCE;
GRANT SELECT ON NEPS.REF_COPYSTREET TO MARKETING;
GRANT DELETE, INSERT, UPDATE ON NEPS.REF_COPYSTREET TO SUPERVISOR;

INSERT INTO REF_COPYSTREET VALUES (5100);
INSERT INTO REF_COPYSTREET VALUES (5200);
INSERT INTO REF_COPYSTREET VALUES (5400);
INSERT INTO REF_COPYSTREET VALUES (9100);
INSERT INTO REF_COPYSTREET VALUES (9300);
INSERT INTO REF_COPYSTREET VALUES (9400);
INSERT INTO REF_COPYSTREET VALUES (9500);
INSERT INTO REF_COPYSTREET VALUES (9600);
INSERT INTO REF_COPYSTREET VALUES (9700);
INSERT INTO REF_COPYSTREET VALUES (5600);

COMMIT;

--23-Sep-2012
DELETE from REF_COPYSTREET;

ALTER TABLE NEPS.REF_COPYSTREET ADD (CODE  VARCHAR2(100 BYTE) NOT NULL);

Insert into REF_COPYSTREET   (FNO, CODE) Values   ('9900', 'DB_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('9700', 'FAN_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('9600', 'RT_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('9500', 'MUX_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('9400', 'NDH_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('9300', 'DDN_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('9100', 'RT_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('5900', 'FDP_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('5800', 'FDP_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('5600', 'FDP_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('5500', 'ODF_NUM');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('5400', 'UPE_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('5200', 'EPE_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('5100', 'FDC_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('4900', 'PATCH_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('4800', 'NODE_CODE');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('13000', 'DP_NUM');
Insert into REF_COPYSTREET   (FNO, CODE) Values   ('12200', 'PATCH_CODE');

COMMIT;

--16-Oct-2012
ALTER TABLE NEPS.REF_COPYSTREET ADD (CNO NUMBER(5));

Update REF_COPYSTREET a set CNO = (select c.g3e_cno from g3e_component c, g3e_featurecomponent f where f.g3e_cno = c.g3e_cno and lower(g3e_username) like '%address geo%' and a.fno = f.g3e_fno);




