grant select on G3E_DUCTIFACE to designer;
grant select on G3E_DUCTFORMATION to designer;

CREATE PUBLIC SYNONYM G3E_DUCTFORMATION FOR NEPS.G3E_DUCTFORMATION;
CREATE PUBLIC SYNONYM G3E_DUCTIFACE FOR NEPS.G3E_DUCTIFACE;

update G3E_DUCTIFACE set G3E_PARAMETER1=0.055 where G3E_TYPE in ('G3E_IDUCT_DHSPACING','G3E_IDUCT_DVSPACING');
commit;
