---Copy Manhole CustomCommand
 Insert into G3E_CUSTOMCOMMAND
   (G3E_CCNO, G3E_USERNAME, G3E_DESCRIPTION, G3E_AUTHOR, G3E_LARGEBITMAP, G3E_SMALLBITMAP, G3E_TOOLTIP, G3E_COMMANDCLASS, G3E_ENABLINGMASK, G3E_MODALITY, G3E_SELECTSETENABLINGMASK, G3E_MENUORDINAL, G3E_EDITDATE, G3E_INTERFACE)
 Values
   (G3E_CUSTOMCOMMAND_SEQ.NEXTVAL, 'Copy Manhole', 'Copy Manhole', 'Anna Poe', 0, 0, 'Copy Manhole', 4, 8388624, 0, 0, 1, SYSDATE, 'NEPSCopyCivilManhole:NEPS.GTechnology.NEPSCopyManhole.GTCopyCivilManhole');
 COMMIT;