ALTER TABLE B$GC_ITFACE ADD (PCAB_CODE			VARCHAR2(4));

EXEC CONSTRAINT_TRANSFER.GETPRIMARYCONSTRAINT ('B$GC_ITFACE');
EXEC CONSTRAINT_TRANSFER.DROPUNIQUECONSTRAINT ('B$GC_ITFACE');
EXEC CONSTRAINT_TRANSFER.DROPUNIQUECONSTRAINT ('B$GC_ITFACE');
EXEC CONSTRAINT_TRANSFER.DROPUNIQUEINDEX ('B$GC_ITFACE');
EXEC CREATE_VIEWS.CREATE_LTT_VIEW ('B$GC_ITFACE');
EXEC CREATE_TRIGGERS.CREATE_LTT_TRIGGER ('B$GC_ITFACE');
EXEC GDOTRIGGERS.CREATE_GDOTRIGGERS ('B$GC_ITFACE');

DECLARE
	v_G3E_ANO	G3E_ATTRIBUTE.G3E_ANO%TYPE;
	v_G3E_CNO	G3E_ATTRIBUTE.G3E_CNO%TYPE := 10301;
BEGIN
	v_G3E_ANO := 1030136;
	INSERT INTO G3E_ATTRIBUTE (G3E_ANO, G3E_CNO, G3E_VNO, G3E_FORMAT, G3E_DATATYPE, G3E_REQUIRED, G3E_HYPERTEXT, G3E_COPY, G3E_EXCLUDEFROMEDIT, G3E_EXCLUDEFROMREPLACE, G3E_BREAKCOPY, G3E_COPYATTRIBUTE, G3E_WRAPTEXT, G3E_UNIQUE, G3E_FIELD, G3E_USERNAME) 
	VALUES (v_G3E_ANO + 1, v_G3E_CNO, NULL, NULL,10, 0, 0, 0, 1, 0, 0, 0, 1, 0, 'PCAB_CODE', 'PCAB Code');
	COMMIT;
END;
/
