DROP TABLE IF EXISTS AG_CABLE_JOINT;

-- create table
CREATE TABLE AG_CABLE_JOINT
(
  ID				NUMBER PRIMARY KEY,
  ACTIVE_JOB		VARCHAR2(30),
  CABLE_FID			NUMBER(10),
  JOINT_FID	  		NUMBER(10),
  ITFACE_CODE		VARCHAR2(30),
  CABLE_CODE		VARCHAR2(30),
  CTYPE				VARCHAR2(30),
  TOTAL_SIZE		NUMBER(38),
  GAUGE             NUMBER(4,2)
);

-- create auto increment sequence for the primary key
CREATE SEQUENCE AG_CABLE_JOINT_SEQ
START WITH 1
INCREMENT BY 1;

-- create synonym to enable other user to access the data
CREATE OR REPLACE PUBLIC SYNONYM AG_CABLE_JOINT_SEQ FOR NEPS.AG_CABLE_JOINT_SEQ;
GRANT SELECT ON NEPS.AG_CABLE_JOINT_SEQ TO DESIGNER;

CREATE OR REPLACE PUBLIC SYNONYM AG_CABLE_JOINT FOR NEPS.AG_CABLE_JOINT;
GRANT SELECT, INSERT, DELETE, UPDATE ON NEPS.AG_CABLE_JOINT TO DESIGNER;
