DECLARE
	v_G3E_RINO	G3E_FEATURE.G3E_RINO%TYPE := 7000;
BEGIN
	-- Cable
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 7000;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 7000;
	
	-- Cabinet
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 10300;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 10300;
	
	-- PDP
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 13100;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 13100;

	-- Exchange
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6000;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6000;
	
	-- Splice/Joint
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 10800;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 10800;

	-- PDDP
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6200;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6200;
	
	-- DDP
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6300;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6300;
	
	-- Contactor Gauge
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6400;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6400;
	
	-- Contactor Alarm
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6500;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6500;
	
	-- Gas Seal
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6600;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6600;

	-- Test Point
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6700;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6700;

	-- Loading Coil
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6800;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6800;
	
	-- Transducer
	UPDATE G3E_FEATURE SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6900;
	UPDATE G3E_PLACEMENTCONFIGURATION SET G3E_RINO = v_G3E_RINO WHERE G3E_FNO = 6900;
	
END;
/

COMMIT;
