INSERT INTO G3E_ATTRIBUTE (G3E_ANO,G3E_CNO,G3E_USERNAME, G3E_FIELD, G3E_REQUIRED, G3E_HYPERTEXT, G3E_COPY, G3E_EXCLUDEFROMEDIT, G3E_DATATYPE, G3E_EXCLUDEFROMREPLACE,
G3E_EDITDATE, G3E_BREAKCOPY, G3E_COPYATTRIBUTE, G3E_WRAPTEXT, G3E_UNIQUE, G3E_FUNCTIONALVALIDATION, G3E_ROLE)
VALUES (700135, 7001, 'CABLE_CODE', 'Cable Code', 0, 0, 0, 1, 10, 0, SYSDATE, 0, 0, 1, 0, 1, 'EVERYONE');
 
INSERT INTO G3E_ATTRIBUTE (G3E_ANO, G3E_CNO, G3E_FIELD, G3E_USERNAME, G3E_REQUIRED, G3E_HYPERTEXT, G3E_COPY, G3E_EXCLUDEFROMEDIT, G3E_DATATYPE, G3E_EXCLUDEFROMREPLACE,
 G3E_EDITDATE, G3E_BREAKCOPY, G3E_COPYATTRIBUTE, G3E_WRAPTEXT, G3E_UNIQUE, G3E_FUNCTIONALVALIDATION, G3E_ROLE)
 VALUES (7742, 77, 'CABLE_CODE', 'Cable Code', 0, 0, 0, 0, 10, 0, SYSDATE, 0, 1, 1, 0, 0, 'EVERYONE');
 
